name: chat1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  firebase_storage: ^11.6.0
  firebase_core: ^2.25.4
  cloud_firestore: ^4.14.0
  provider: ^6.1.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  image_picker: ^1.0.7
  fluttertoast: any
  photo_view: ^0.14.0
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.2
  flutter_facebook_auth: ^6.1.1
  firebase_messaging: any
  go_router: ^13.2.0
  get: ^4.6.6
  url_launcher: ^6.2.5
  country_code_picker: ^3.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  change_app_package_name: 1.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/image/app_icon/
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/app_icon/app_icon.png"
  min_sdk_android: 21
